name: Build VSCode Extension

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install vsce tool globally
        run: npm install -g vsce

      - name: Package VSCode extension
        run: vsce package

      - name: Upload VSIX package as artifact
        uses: actions/upload-artifact@v3
        with:
          name: siemens-alarm-highlighter
          path: '*.vsix'
